### PR TITLE
Fix DOS line endings parsing

### PR DESCRIPTION
**Pull request by trntv**

### CODE REVIEW

**Comment by kevinburke** [comment]
LGTM. Can we add a test to protect against regressions?

**Comment by Zougi** [comment]
Hey! I'm not a go developer but I guess the command to execute tests is `go test`. none pass, all fails on master branch. on this branch 2 tests fails

**Comment by trntv** [comment]
i'll check it

ср, 14 мар. 2018 г., 04:00 Frederic R. <notifications@github.com>:

**Comment by trntv** [comment]
done

**Comment by Zougi** [comment]
Hey! @kevinburke Tests indeed pass on windows with this change. Thank you @trntv

**Comment by kevinburke** [comment]
merged as fe204ef364e0cbeb969255bf3e8fa70416a31ec6, thanks!

**Pull request closed without merging**
